"""test

Revision ID: 7150f435b130
Revises: 8feba263d722
Create Date: 2017-02-25 12:07:33.458406

"""

# revision identifiers, used by Alembic.
revision = '7150f435b130'
down_revision = '8feba263d722'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('twitch_id', sa.String(length=48), server_default=sa.text('NULL'), nullable=True))
    op.create_index(op.f('ix_tb_user_twitch_id'), 'tb_user', ['twitch_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_user_twitch_id'), table_name='tb_user')
    op.drop_column('tb_user', 'twitch_id')
    # ### end Alembic commands ###
